% MIT License
% 
% Copyright (c) 2017 The Scientific Computing and Imaging Institute
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.



function necFields = get_necFields
% whenever a SCRIPTDATA file is loaded, it is checked if these fields are in the loaded SCRIPTDATA struct
% if any of these necFields is missing, a warning is issued and the file is not loaded
necFields = {'SCRIPTFILE','','file',...
                'DATAFILE','','file',...
                'ACQDIR','','file',...
                'DO_CALIBRATE',1,'bool',...
                'DO_BLANKBADLEADS',1,'bool',...
                'DO_SLICE',1,'bool',...
                'DO_SLICE_USER',1,'bool',...
                'DO_ADDBADLEADS',0,'bool',...
                'DO_SPLIT',1,'bool',...
                'DO_BASELINE',1,'bool',...
                'DO_BASELINE_RMS',0,'bool',...
                'DO_BASELINE_USER',1,'bool',...
                'DO_DETECT',1,'bool',...
                'DO_DETECT_USER',1,'bool',...
                'DO_INTEGRALMAPS',1,'bool',...
                'DO_ACTIVATIONMAPS',1,'bool',...
                'DO_FILTER',0,'bool'
        };
end